export const products = {
  "iq-wall": {
    id: "iq-wall",
    name: "IQ-Wall 4×4",
    description: "Отдельностоящая реконфигурируемая видеостена",
    model: "/models/4x4_freestanding_reconfigurable_iq-wall.glb",
    category: "screens",
    rotation: 0,
  },
  "meeting-table": {
    id: "meeting-table",
    name: "Интерактивный стол 84″",
    description: "Сенсорный стол для переговорных и презентаций",
    model: "/models/84_interactive_meeting_table.glb",
    category: "tables",
    rotation: Math.PI / 2,
  },
  "paykiosk": {
    id: "paykiosk",
    name: "Платёжный киоск",
    description: "Терминал самообслуживания с оплатой",
    model: "/models/eud_paykiosk.glb",
    category: "kiosks",
    rotation: Math.PI,
  },
  "stand-roof": {
    id: "stand-roof",
    name: "Стенд 2.0 с крышей",
    description: "Выставочный стенд с навесной конструкцией",
    model: "/models/eud_stand_2.0_roof.glb",
    category: "stands",
    rotation: Math.PI,
  },
  "stand-panel": {
    id: "stand-panel",
    name: "Стенд с панелью",
    description: "Компактный выставочный стенд с экраном",
    model: "/models/eud_stand_panel.glb",
    category: "stands",
    rotation: Math.PI,
  },
  "touch-skola": {
    id: "touch-skola",
    name: "Extra Touch Школа",
    description: "Интерактивная панель для образования",
    model: "/models/extra_touch_-_skola.glb",
    category: "panels",
    rotation: Math.PI,
  },
  "touch-double": {
    id: "touch-double",
    name: "Extra Touch Double",
    description: "Двусторонняя интерактивная панель",
    model: "/models/extra_touch_double.glb",
    category: "panels",
    rotation: 0,
  },
  "led-stand": {
    id: "led-stand",
    name: "LED Stand Panel",
    description: "Стойка с LED-панелью",
    model: "/models/led_stand_panel.glb",
    category: "screens",
    rotation: Math.PI,
  },
  "monitoring-station": {
    id: "monitoring-station",
    name: "Monitoring Station",
    description: "Станция мониторинга с несколькими экранами",
    model: "/models/monitoring_station.glb",
    category: "screens",
    rotation: -Math.PI / 2,
  },
  "scifi-kiosk": {
    id: "scifi-kiosk",
    name: "Sci-Fi Kiosk",
    description: "Футуристический информационный киоск",
    model: "/models/scifi_kiosk.glb",
    category: "kiosks",
    rotation: 0,
  },
  "tv-wall": {
    id: "tv-wall",
    name: "Настенный ТВ",
    description: "Настенный телевизор / дисплей",
    model: "/models/television_wall-mounted.glb",
    category: "screens",
    rotation: 0,
  },
}

export const categories = {
  all: "Все",
  panels: "Панели",
  tables: "Столы",
  kiosks: "Киоски",
  screens: "Экраны",
  stands: "Стенды",
}
